baseURL = 'https://pexcode.org/'
title = 'PexCode.org'

languageCode = "en"
DefaultContentLanguage = "en"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[params]
contactFormAction = "https://formspree.io/f/movabokp"
author = "PexCode ðŸ’–"
profilePicture = "images/profile.jpg"
description = """
This association ðŸ’¡ fuels IT grads with:
â€¢ Real-world projects ðŸ› 
â€¢ Skill-packed workshops ðŸŽ“
â€¢ Collaboration ðŸ¤ 
to supercharge their career journey ðŸš€.
"""
contentratio = 0.75 
favicon = "favicons/"
mainSections = ["posts"]


[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:contact@pexcode.org"

[[params.socialIcons]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/company/pexcode-org"

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false