[en]
title = "My blog"
weight = 1
LanguageName = "EN"
contentDir = "content/en"

[fr]
title = "Mon Blog"
weight = 2
LanguageName = "FR"
contentDir = "content/fr" 
[fr.params]
description = """
Cette association ğŸ’¡ propulse les diplÃ´mÃ©s en informatique avec :
â€¢ Des projets concrets ğŸ› 
â€¢ Des ateliers riches en compÃ©tences ğŸ“
â€¢ Des opportunitÃ©s de collaboration ğŸ¤
pour dynamiser leur parcours professionnel ğŸš€.
"""