baseURL = 'https://pexcode.org/'
languageCode = 'en-us'
title = 'DevsAsso'

[params]
#contactFormAction = "https://formspree.io/f/movabokp"
author = "PexCode ðŸ’–"
profilePicture = "images/profile.jpg"
description = """
This association ðŸ’¡ fuels IT grads with:
â€¢ Real-world projects ðŸ› 
â€¢ Skill-packed workshops ðŸŽ“
â€¢ Collaboration ðŸ¤ 
to supercharge their career journey ðŸš€.
"""

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:contact@pexcode.org"

[[params.socialIcons]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/company/pexcode-org"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false